version: "3"

volumes:
  local_django_ghost_postgres_data: {}
services:
  django: &django # enables use of pdb
    hostname: django
    stdin_open: true
    tty: true
    build:
      context: ../
      dockerfile: ./docker/django.Dockerfile
    image: django_ghost
    container_name: django_ghost__django
    depends_on:
      - postgres
      - nats
    volumes:
      - ../:/workspace:z
    ports:
      - "8801:8000"
    env_file:
      - .env
    command:
      - ./start
  postgres:
    hostname: postgres
    image: postgres:14
    container_name: django_ghost__postgres
    volumes:
      - local_django_ghost_postgres_data:/var/lib/postgresql/data:z
    env_file:
      - .env
    ports:
      - "5433:5432"
  ghost:
    hostname: ghost
    container_name: django_ghost__ghost
    image: ghost:5.22
    ports:
      - "2368:2368"
    environment:
      NODE_ENV: development
    volumes:
      - ../data:/var/lib/ghost/content:z
